# Deletar Release: dai é possível criar uma!
# https://github.com/dev-drprasad/delete-tag-and-release

name: Delete Tags and Releases

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          #tag_name: 'v1.0' # tag name to delete
          #repo: <repoOwner>/<repoName> # target repo (optional). defaults to repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
