# https://github.com/softprops/action-gh-release
# Notei que só aceita pushs com tags
# Notei que ele escreve apenas uma release e não há como sobrepor
# Faz-se necessário criar outra tag e inserir novo arquivo.

name: Create Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pega Arquivos
      - name: Checkout
        uses: actions/checkout@v2

      # Cria Release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') #
        with: # Optional
          name: 'data'
          body: 'Dados do InfoÁguas obtidos em 25.10.2021'
          files: |
            LICENSE
            ftp_action/index.html
