# https://stackoverflow.com/questions/60963759/use-github-actions-to-create-a-tag-but-not-a-release
# Não sobrepõe! 

name: Releases

on: 
  push:
    tags:
    - '*'
    # branches:
    # - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Pega Arquivos
    - name: Checkout    
      uses: actions/checkout@v2

    # dddd
    - name: Release snapshot
      id: release-snapshot
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v1.2'
        release_name: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false