# Clonar repo do GitHub para repo do Azure
# Necessário que os repos tenham o mesmo nome
# https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
# https://stackoverflow.com/questions/61229061/how-to-synchronize-github-and-azure-devops-repository
# Michel Metran
# Data: 05.10.2024
# Atualizado em: 05.10.2024

name: Clone to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git
        run: sudo apt-get install git

      - name: Setup Git
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'github'

      - name: Remove .git
        run: |
          cd github
          rm -rf .git
          rm -rf .github

      - name: Clone Azure Repository
        run: |
          mkdir $GITHUB_WORKSPACE/devops
          cd $GITHUB_WORKSPACE/devops
          git clone https://$AZURE_DEVOPS_PAT@dev.azure.com/Michel-Silva/MyDevOps/_git/${{ GITHUB.EVENT.REPOSITORY.NAME }}

        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Copy Files
        run: |
          cp -r $GITHUB_WORKSPACE/github/. $GITHUB_WORKSPACE/devops/${{ GITHUB.EVENT.REPOSITORY.NAME }}/

      - name: Git Add, Commit and Push
        run: |
          # Entra na pasta
          cd $GITHUB_WORKSPACE/devops/${{ GITHUB.EVENT.REPOSITORY.NAME }}/

          git add .
          #git commit -m "Sync from $URL/$REPO"
          git commit -m "Sync Repo"
          git push
        env:
          URL: ${{ GITHUB.SERVER_URL }}
          REPO: ${{ GITHUB.REPOSITORY }}
