# Clonar repo do GitHub para repo do Azure
# https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
# https://stackoverflow.com/questions/61229061/how-to-synchronize-github-and-azure-devops-repository
# Michel Metran
# Data: 05.10.2024
# Atualizado em: 05.10.2024

name: Clone to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git
        run: sudo apt-get install git

      - name: Setup Git
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          echo ${{ GITHUB.EVENT.REPOSITORY.NAME }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'github'

      - name: Remove .git
        run: |
          #pwd
          #ls -la
          cd github
          rm -rf .git
          #ls -la

      - name: Clone Azure Repository
        run: |
          #pwd
          cd ..          
          #echo $GITHUB_WORKSPACE
          mkdir $GITHUB_WORKSPACE/devops
          cd $GITHUB_WORKSPACE/devops
          git clone $AZURE_DEVOPS_URL
          #pwd
          #ls -la

        env:
          AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_URL }}

      - name: Copy
        run: |
          #pwd
          cp -r $GITHUB_WORKSPACE/github/* $GITHUB_WORKSPACE/devops/${{ GITHUB.EVENT.REPOSITORY.NAME }}/
          # Entra na pasta
          cd $GITHUB_WORKSPACE/devops/${{ GITHUB.EVENT.REPOSITORY.NAME }}/
          #ls -la
          #pwd

      - name: Git Add
        run: |
          cd $GITHUB_WORKSPACE/devops/${{ GITHUB.EVENT.REPOSITORY.NAME }}/
          #pwd
          #ls -la

          git add .
          git commit -m "Sync from git to azure"
          git push

      # - name: Add remote
      #   run: |
      #     git remote add azure https://github.com/michelmetran/github_actions_personal.git

      # - name: Git Update
      #   run: |
      #     git remote update

      # - name: Git Merge
      #   run: |
      #     git merge azure/main

      # - name: Outros
      #   run: |
      #     git push origin main
