# Clonar repo do GitHub para repo do Azure
# https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
# 
# Michel Metran
# Data: 05.10.2024
# Atualizado em: 05.10.2024

name: Clone to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git
      
      - name: Setup Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Clone Repository
        run: |
          git clone $AZURE_DEVOPS_URL
          #git clone https://github.com/michelmetran/github_actions_personal.git
        env:
          AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_URL }}
  
      - name: Get Inside Folder
        run: |
          #cd github_actions_personal
          cd teste_action_clone

      - name: Add remote
        run: |
          git remote add azure https://github.com/michelmetran/github_actions_personal.git
          #git remote add azure $AZURE_DEVOPS_URL
        env:
          AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_URL }}

      - name: Git Update
        run: |
          git remote update

      - name: Git Merge
        run: |
          git merge azure/main
          # git merge main

      - name: Outros        
        run: |
          git push origin main
        # env:
        #   AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_URL }}
          #AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

