# https://github.com/dmnemec/copy_file_to_another_repo_action

name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './data/ftp_action/css/css.cssmd'
        destination_repo: 'michelmetran/github_actions_output'
        destination_folder: 'test-dir'
        user_email: 'michelmetran@email.com'
        user_name: 'michelmetran'
        commit_message: 'A custom message for the commit'

